import { 
  CHANGE_FONTS 
}  from '../actions/types';

const desktopW = 1440;
const mobileW = 375;
const mobileH = 250;

function fontSize(screenWidth, initSize, mobile) {
  if(mobile) 
    return Math.round(screenWidth*initSize/mobileW)
  
  return initSize; //Math.round(screenWidth*initSize/desktopW)
}

  const INITIAL_STATE = {
    SubTitleGrandeHERO:{fontSize:16, fontSizeM:14}, 
    TitleGrandeHERO:{fontSize:50, fontSizeM:24},
    ScrollDownText:{fontSize:16, fontSizeM:10,},
    ScrollDownArrow:{size:79, sizeM:47},
    BackgroundImage:{height:662, heightM:250},
    InfoHeaderTitle:{fontSize:12, fontSizeM:12},
    InfoHeaderTime:{fontSize:10, fontSizeM:10},
    Collapse: {fontSize:12, fontSizeM:12},
    HamburgerMenu: {fontSizeM:30},
    Info: {size:44},
    ParagraphText: { fontSize:18, fontSizeM:13},
    ParagraphTitle: { fontSize:35, fontSizeM:18},
    CollapseIcon: {size:10},
    ContainerTitle1: {fontSize: 16, fontSizeM: 12},
    ContainerTitle4: {fontSize: 35, fontSizeM: 18},
    ContainerTitle2: {fontSize: 28, fontSizeM: 18},
    ContainerText: {fontSize: 16, fontSizeM: 16},
    QuoteText: {fontSize: 40, fontSizeM: 24},
    InfoWeather1: {fontSize: 20, fontSizeM: 24},
    InfoWeather2: {fontSize: 16, fontSizeM: 20},
    InfoWeather3: {fontSize: 12, fontSizeM: 15},
    InfoLocation1: {fontSize: 12, fontSizeM: 15},
    InfoLocation2: {fontSize: 12, fontSizeM: 15},
    BoxTitle: {fontSize: 35, fontSizeM: 18},
    BoxText: {fontSize: 16, fontSizeM: 11},
    BoxFooter: {fontSize: 14, fontSizeM: 10},
    BoxButtonText: {fontSize: 16, fontSizeM: 11},
    ProgramDetailTitle1: {fontSize: 50, fontSizeM: 35},
    ProgramDetailTitle2: {fontSize: 16, fontSizeM: 11},
    ProgramDetailLink1: {fontSize: 12, fontSizeM: 14},
    ProgramDetailTitle3:  {fontSize: 16, fontSizeM: 11},
    NewsDetailText1:  {fontSize: 16, fontSizeM: 11},
    NewsDetailText2:  {fontSize: 28, fontSizeM: 18},
    NewsDetailText3:  {fontSize: 16, fontSizeM: 11},
    BoxCourseRow1Text:  {fontSize: 30, fontSizeM: 18},
    BoxCourseRow2Text:  {fontSize: 16, fontSizeM: 11},
    BoxCourseRow3Text:  {fontSize: 16, fontSizeM: 11},
    FooterInfoTitle:  {fontSize: 21, fontSizeM: 25},
    FooterInfoFont1:  {fontSize: 14, fontSizeM: 11},
    FooterInfoFont2:  {fontSize: 14, fontSizeM: 10},
    FooterInfoFont3:  {fontSize: 14, fontSizeM: 11},
    FooterText:  {fontSize: 14, fontSizeM: 11},
    NewsButtonText:  {fontSize: 16, fontSizeM: 11},
    NewsColumnText1:  {fontSize: 21, fontSizeM: 19},
    NewsColumnText2:  {fontSize: 16, fontSizeM: 11},
    NewsColumnText4:  {fontSize: 28, fontSizeM: 18},
    NewsColumnText5:  {fontSize: 16, fontSizeM: 11},
    NewsColumnDate :  {fontSize: 16, fontSizeM: 11},
    NewsColumn3Title :  {fontSize: 21, fontSizeM: 19},
    GalleryTitle:  {fontSize: 28, fontSizeM: 18},
    SuperTitlePrograms:  {fontSize: 16, fontSizeM: 11},
    TitlePrograms: { fontSize:35, fontSizeM:18},
    PrinciplesText1: {fontSize: 16, fontSizeM: 11},
    PrinciplesText2: {fontSize: 32, fontSizeM: 18},
    PrinciplesNumbers: {fontSize: 16, fontSizeM: 11},
    TrainerName: {fontSize: 16, fontSizeM: 11},
    BoxSkillText: {fontSize: 22, fontSizeM: 20},
  };
  
  export default (state = INITIAL_STATE, action) => {
  
    
    switch (action.type) {
      case CHANGE_FONTS: 
          const {screenWidth, screenHeight, mobile} = action.payload;
        return { 
          state, 
          screenWidth,
          screenHeight,
          SubTitleGrandeHERO:{fontSize: fontSize(screenWidth,
            mobile?INITIAL_STATE.SubTitleGrandeHERO.fontSizeM:INITIAL_STATE.SubTitleGrandeHERO.fontSize,
            mobile)},
          TitleGrandeHERO:{fontSize: fontSize(screenWidth,
            mobile?INITIAL_STATE.TitleGrandeHERO.fontSizeM:INITIAL_STATE.TitleGrandeHERO.fontSize,mobile)},
          ScrollDownText: {fontSize: fontSize(screenWidth,
            mobile?INITIAL_STATE.ScrollDownText.fontSizeM:INITIAL_STATE.ScrollDownText.fontSize,mobile)},
          ScrollDownArrow: {size: mobile? screenWidth*47/mobileW: screenWidth/desktopW*79},
          BackgroundImage: { height: mobile?screenWidth*mobileH/mobileW:662},
          InfoHeaderTitle: {fontSize: fontSize(screenWidth, INITIAL_STATE.InfoHeaderTitle.fontSize,mobile)},
          InfoHeaderTime: {fontSize:  fontSize(screenWidth, INITIAL_STATE.InfoHeaderTime.fontSize,mobile)},
          Collapse: {fontSize: fontSize(screenWidth, INITIAL_STATE.Collapse.fontSize,mobile)},
          Info: {size: mobile? fontSize(screenWidth, INITIAL_STATE.InfoHeaderTitle.fontSize,true) -
            INITIAL_STATE.InfoHeaderTitle.fontSize + INITIAL_STATE.Info.size
              :INITIAL_STATE.Info.size},
          CollapseIcon: {size: mobile?Math.round( INITIAL_STATE.CollapseIcon.size*screenWidth/375):10},
          /*
          InfoHeaderTitle: {fontSize: mobile?INITIAL_STATE.InfoHeaderTitle.fontSize:fontSize(screenWidth, INITIAL_STATE.InfoHeaderTitle.fontSize,mobile)},
          InfoHeaderTime: {fontSize:  mobile?INITIAL_STATE.InfoHeaderTime.fontSize:fontSize(screenWidth, INITIAL_STATE.InfoHeaderTime.fontSize,mobile)},
          Collapse: {fontSize: mobile?INITIAL_STATE.Collapse.fontSize:fontSize(screenWidth, INITIAL_STATE.Collapse.fontSize,mobile)},
      
          Info: {size: INITIAL_STATE.Info.size},
          */
          HamburgerMenu: {fontSize: INITIAL_STATE.HamburgerMenu.fontSizeM},
          ParagraphTitle: {fontSize:fontSize(screenWidth,
            mobile?INITIAL_STATE.ParagraphTitle.fontSizeM:INITIAL_STATE.ParagraphTitle.fontSize,mobile)},
          ParagraphText: {fontSize:fontSize(screenWidth,
            mobile?INITIAL_STATE.ParagraphText.fontSizeM:INITIAL_STATE.ParagraphText.fontSize,mobile)},
          ContainerTitle1: {fontSize:fontSize(screenWidth,
              mobile?INITIAL_STATE.ContainerTitle1.fontSizeM:INITIAL_STATE.ContainerTitle1.fontSize,mobile)},
          ContainerTitle2: {fontSize:fontSize(screenWidth,
                mobile?INITIAL_STATE.ContainerTitle2.fontSizeM:INITIAL_STATE.ContainerTitle2.fontSize,mobile)},
          ContainerTitle4: {fontSize:fontSize(screenWidth,
                  mobile?INITIAL_STATE.ContainerTitle4.fontSizeM:INITIAL_STATE.ContainerTitle4.fontSize,mobile)},
          ContainerText: {fontSize:fontSize(screenWidth,
                  mobile?INITIAL_STATE.ContainerText.fontSizeM:INITIAL_STATE.ContainerText.fontSize,mobile)},
          QuoteText: {fontSize:fontSize(screenWidth,
                    mobile?INITIAL_STATE.QuoteText.fontSizeM:INITIAL_STATE.QuoteText.fontSize,mobile)},
          InfoWeather1: {fontSize:fontSize(screenWidth,
                      mobile?INITIAL_STATE.InfoWeather1.fontSizeM:INITIAL_STATE.InfoWeather1.fontSize,mobile)},
          InfoWeather2: {fontSize:fontSize(screenWidth,
                        mobile?INITIAL_STATE.InfoWeather2.fontSizeM:INITIAL_STATE.InfoWeather2.fontSize,mobile)},
          InfoWeather3: {fontSize:fontSize(screenWidth,
                          mobile?INITIAL_STATE.InfoWeather3.fontSizeM:INITIAL_STATE.InfoWeather3.fontSize,mobile)},
          InfoLocation1: {fontSize:fontSize(screenWidth,
            mobile?INITIAL_STATE.InfoLocation1.fontSizeM:INITIAL_STATE.InfoLocation1.fontSize,mobile)},
          InfoLocation2: {fontSize:fontSize(screenWidth,
              mobile?INITIAL_STATE.InfoLocation2.fontSizeM:INITIAL_STATE.InfoLocation2.fontSize,mobile)},
          BoxText: {fontSize:fontSize(screenWidth,
            mobile?INITIAL_STATE.BoxText.fontSizeM:INITIAL_STATE.BoxText.fontSize,mobile)},
          BoxTitle: {fontSize:fontSize(screenWidth,
              mobile?INITIAL_STATE.BoxTitle.fontSizeM:INITIAL_STATE.BoxTitle.fontSize,mobile)},
          BoxFooter: {fontSize:fontSize(screenWidth,
            mobile?INITIAL_STATE.BoxFooter.fontSizeM:INITIAL_STATE.BoxFooter.fontSize,mobile)},
          BoxButtonText: {fontSize:fontSize(screenWidth,
              mobile?INITIAL_STATE.BoxButtonText.fontSizeM:INITIAL_STATE.BoxButtonText.fontSize,mobile)},
          ProgramDetailTitle1: {fontSize:fontSize(screenWidth,
                mobile?INITIAL_STATE.ProgramDetailTitle1.fontSizeM:INITIAL_STATE.ProgramDetailTitle1.fontSize,mobile)},
          ProgramDetailTitle2: {fontSize:fontSize(screenWidth,
                  mobile?INITIAL_STATE.ProgramDetailTitle2.fontSizeM:INITIAL_STATE.ProgramDetailTitle2.fontSize,mobile)},
          ProgramDetailLink1: {fontSize:fontSize(screenWidth,
                    mobile?INITIAL_STATE.ProgramDetailLink1.fontSizeM:INITIAL_STATE.ProgramDetailLink1.fontSize,mobile)},
          ProgramDetailTitle3:{fontSize:fontSize(screenWidth,
                      mobile?INITIAL_STATE.ProgramDetailTitle3.fontSizeM:INITIAL_STATE.ProgramDetailTitle3.fontSize,mobile)},
          NewsDetailText1: { fontSize:fontSize(screenWidth,
                        mobile?INITIAL_STATE.NewsDetailText1.fontSizeM:INITIAL_STATE.NewsDetailText1.fontSize,mobile)},
          NewsDetailText2: { fontSize:fontSize(screenWidth,
                          mobile?INITIAL_STATE.NewsDetailText2.fontSizeM:INITIAL_STATE.NewsDetailText2.fontSize,mobile)},
          NewsDetailText3: { fontSize:fontSize(screenWidth,
                            mobile?INITIAL_STATE.NewsDetailText3.fontSizeM:INITIAL_STATE.NewsDetailText3.fontSize,mobile)},
          BoxCourseRow1Text: { fontSize:fontSize(screenWidth,
                              mobile?INITIAL_STATE.BoxCourseRow1Text.fontSizeM:INITIAL_STATE.BoxCourseRow1Text.fontSize,mobile)},
          BoxCourseRow2Text: { fontSize:fontSize(screenWidth,
                                mobile?INITIAL_STATE.BoxCourseRow2Text.fontSizeM:INITIAL_STATE.BoxCourseRow2Text.fontSize,mobile)},
          BoxCourseRow3Text: { fontSize:fontSize(screenWidth,
                                  mobile?INITIAL_STATE.BoxCourseRow3Text.fontSizeM:INITIAL_STATE.BoxCourseRow3Text.fontSize,mobile)},
          FooterInfoTitle: { fontSize:fontSize(screenWidth,
                                    mobile?INITIAL_STATE.FooterInfoTitle.fontSizeM:INITIAL_STATE.FooterInfoTitle.fontSize,mobile)},
          FooterInfoFont1: { fontSize:fontSize(screenWidth,
          mobile?INITIAL_STATE.FooterInfoFont1.fontSizeM:INITIAL_STATE.FooterInfoFont1.fontSize,mobile)},
          FooterInfoFont2: { fontSize:fontSize(screenWidth,
            mobile?INITIAL_STATE.FooterInfoFont2.fontSizeM:INITIAL_STATE.FooterInfoFont2.fontSize,mobile)},
          FooterInfoFont3: { fontSize:fontSize(screenWidth,
              mobile?INITIAL_STATE.FooterInfoFont3.fontSizeM:INITIAL_STATE.FooterInfoFont3.fontSize,mobile)},
          FooterText: { fontSize:fontSize(screenWidth,
                mobile?INITIAL_STATE.FooterText.fontSizeM:INITIAL_STATE.FooterText.fontSize,mobile)},
          NewsButtonText: { fontSize:fontSize(screenWidth,
                  mobile?INITIAL_STATE.NewsButtonText.fontSizeM:INITIAL_STATE.NewsButtonText.fontSize,mobile)},          
          NewsColumnText1: { fontSize:fontSize(screenWidth,
            mobile?INITIAL_STATE.NewsColumnText1.fontSizeM:INITIAL_STATE.NewsColumnText1.fontSize,mobile)},
          NewsColumnText2: { fontSize:fontSize(screenWidth,
              mobile?INITIAL_STATE.NewsColumnText2.fontSizeM:INITIAL_STATE.NewsColumnText2.fontSize,mobile)},
          NewsColumnText4: { fontSize:fontSize(screenWidth,
                mobile?INITIAL_STATE.NewsColumnText4.fontSizeM:INITIAL_STATE.NewsColumnText4.fontSize,mobile)},
          NewsColumnText5: { fontSize:fontSize(screenWidth,
                  mobile?INITIAL_STATE.NewsColumnText5.fontSizeM:INITIAL_STATE.NewsColumnText5.fontSize,mobile)},
          NewsColumnDate: { fontSize:fontSize(screenWidth,
                    mobile?INITIAL_STATE.NewsColumnDate.fontSizeM:INITIAL_STATE.NewsColumnDate.fontSize,mobile)},
          NewsColumn3Title: { fontSize:fontSize(screenWidth,
                      mobile?INITIAL_STATE.NewsColumn3Title.fontSizeM:INITIAL_STATE.NewsColumn3Title.fontSize,mobile)},
          GalleryTitle: { fontSize:fontSize(screenWidth,
                        mobile?INITIAL_STATE.GalleryTitle.fontSizeM:INITIAL_STATE.GalleryTitle.fontSize,mobile)},
          SuperTitlePrograms: { fontSize:fontSize(screenWidth,
                          mobile?INITIAL_STATE.SuperTitlePrograms.fontSizeM:INITIAL_STATE.SuperTitlePrograms.fontSize,mobile)},
          TitlePrograms:  { fontSize:fontSize(screenWidth,
                            mobile?INITIAL_STATE.TitlePrograms.fontSizeM:INITIAL_STATE.TitlePrograms.fontSize,mobile)},
          PrinciplesText1: { fontSize:fontSize(screenWidth,
                              mobile?INITIAL_STATE.PrinciplesText1.fontSizeM:INITIAL_STATE.PrinciplesText1.fontSize,mobile)},
          PrinciplesText2: { fontSize:fontSize(screenWidth,
                            mobile?INITIAL_STATE.PrinciplesText2.fontSizeM:INITIAL_STATE.PrinciplesText2.fontSize,mobile)},
          PrinciplesNumbers: { fontSize:fontSize(screenWidth,
                              mobile?INITIAL_STATE.PrinciplesNumbers.fontSizeM:INITIAL_STATE.PrinciplesNumbers.fontSize,mobile)},
          TrainerName: { fontSize:fontSize(screenWidth,
                                mobile?INITIAL_STATE.TrainerName.fontSizeM:INITIAL_STATE.TrainerName.fontSize,mobile)},
          BoxSkillText: { fontSize:fontSize(screenWidth,
                           mobile?INITIAL_STATE.BoxSkillText.fontSizeM:INITIAL_STATE.BoxSkillText.fontSize,mobile)},
                           
     
        };     
    default:
        return state;
    }
  }; 

